// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace NUnitTestProject1
{
    [TestFixture]
    public class Demo1Test
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void demo1()
        {
            driver.Navigate().GoToUrl("http://127.0.0.1:8000/product/1/ao-phong-tron/");
            driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
            //driver.FindElement(By.XPath("(//input[@id=\'variantid\'])[3]")).Click();
            //driver.FindElement(By.Id("post-color")).Click();
            //driver.FindElement(By.XPath("(//input[@id=\'variantid\'])[6]")).Click();
            //driver.FindElement(By.Name("quantity")).SendKeys("2");
            //driver.FindElement(By.Name("quantity")).Click();
            //driver.FindElement(By.CssSelector(".button")).Click();
            driver.FindElement(By.CssSelector(".contact_form_title")).Click();
            driver.FindElement(By.Id("contact_form_name")).Click();
            driver.FindElement(By.Id("contact_form_name")).SendKeys("admin");
            driver.FindElement(By.Id("contact_form_email")).SendKeys("admin");
            driver.FindElement(By.CssSelector(".button")).Click();
            driver.FindElement(By.LinkText("Danh sách sản phẩm")).Click();
            driver.FindElement(By.CssSelector(".product_item:nth-child(2) img")).Click();
            driver.FindElement(By.XPath("(//input[@id=\'variantid\'])[2]")).Click();
            driver.FindElement(By.XPath("(//input[@id=\'variantid\'])[6]")).Click();
            driver.FindElement(By.Name("quantity")).SendKeys("2");
            driver.FindElement(By.Name("quantity")).Click();
            driver.FindElement(By.CssSelector(".button")).Click();
            driver.FindElement(By.CssSelector(".alert")).Click();
            driver.FindElement(By.LinkText("Giỏ hàng")).Click();
            driver.FindElement(By.CssSelector(".cart_button_checkout")).Click();
            driver.FindElement(By.Id("bank")).Click();
            driver.FindElement(By.Id("contact_form_name")).Click();
            driver.FindElement(By.Id("contact_form_phone")).Click();
            driver.FindElement(By.Id("school")).Click();
            driver.FindElement(By.Id("bank21")).Click();
            driver.FindElement(By.Id("bank22")).Click();
            driver.FindElement(By.Id("bank23")).Click();
            driver.FindElement(By.Name("total")).Click();
            driver.FindElement(By.Name("total")).Click();
            driver.FindElement(By.CssSelector(".button")).Click();
            driver.FindElement(By.CssSelector("h2:nth-child(3)")).Click();
        }
    }
}

